Repository GSG-FC02/Quran-Apies, pull requests merged in 2021-04, with the labels that each got.

#13 This is full readme file
  README.md
  assets/wireframe.png
Labels: Done

#14 File structure
  Assets/Imges/1 1.png
  Assets/Imges/3 1.png
  Assets/Imges/branding.jpeg
  Assets/Imges/صور-مصاحف14 1.png
  Assets/Imges/مصاحف-وردية-15-cf7ee12f 1.png
  Css/style.css
  Js/script.js
  index.html
Labels: awaiting-review

#15 create home page using html and css
  Css/style.css
  index.html
Labels: Done

#18 6 sourah information
  Js/script.js
  home-page/style.css
  sourah-infornation/sourah.css
  sourah-infornation/sourah.html
Labels: Done

#19 sourah information js file to show information about sourah
  sourah-information/sourah.css
  sourah-information/sourah.html
  sourah-infornation/sourah.js
Labels: Done

#20 These are the html and css files for word-search-page
  word-search-page/word-search-page.css
  word-search-page/word-search-page.html
Labels: Done

#21 This is not complete version of the javascript file for the word-sear…
  read-surah/read-surah.css
  read-surah/read-surah.html
  read-surah/read-surah.js
Labels: Done

#22 creat audio.html audio.css files
  .vscode/settings.json
  audio-Page/audio.css
  audio-Page/audio.html
  audio-Page/audio.js
Labels: Done

#25 all files and images paths were adjusted
  index.html
  read-surah/read-surah.html
  sourah-infornation/sourah.html
Labels: Done

#27 some edits in file paths and remove some attributes
  .vscode/settings.json
  README.md
  audio-Page/audio.css
  audio-Page/audio.html
  index.html
  read-surah/read-surah.css
  read-surah/read-surah.html
  read-surah/read-surah.js
Labels: in-progress

#29 updating the readme file
  README.md
  assets/wireframe.png
  audio-Page/audio.html
Labels: Resolve Conflict

#36 adjusting readme file
  README.md
Labels: awaiting-review

#39 edit responsive
  home-page/style.css
  index.html
  read-surah/read-surah.css
  read-surah/read-surah.html
  sourah-infornation/sourah.css
  sourah-infornation/sourah.html
Labels: in-progress

#41 adjusting audio page for responsive style for laptop
  audio-Page/audio.css
  audio-Page/audio.html
  read-surah/read-surah.css
Labels: awaiting-review

#43 adjusted the image and font size
  read-surah/read-surah.css
  read-surah/read-surah.html
Labels: awaiting-review

#45 adjusting the position of the picture for laptop style
  read-surah/read-surah.css
  read-surah/read-surah.html
Labels: awaiting-review
